
CREATE DATABASE DB_DWPC;

USE DB_DWPC;

  CREATE TABLE IF NOT EXISTS `AUTHORISATION` (
  `AUTHORISATIONID` INT(255)  NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`AUTHORISATIONID`));
  
CREATE TABLE IF NOT EXISTS `USER` (
  `USERID` INT(255)  NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `FK_AUTHORISATIONID` INT(6) DEFAULT NULL,
  PRIMARY KEY (`USERID`),
  FOREIGN KEY (FK_AUTHORISATIONID) REFERENCES AUTHORISATION(AUTHORISATIONID));
  
  CREATE TABLE IF NOT EXISTS `TEMPLATE` (
  `TEMPLATEID` INT(255)  NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) DEFAULT NULL,
  `FK_USERID` INT(6) DEFAULT NULL,
  PRIMARY KEY (`TEMPLATEID`),
  FOREIGN KEY (FK_USERID) REFERENCES USER(USERID));
  
   CREATE TABLE IF NOT EXISTS `CONFIGURATION` (
  `CONFIGURATIONID` INT(255)  NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`CONFIGURATIONID`));
  
  CREATE TABLE IF NOT EXISTS `TEMPLATE_CONFIGURATION` (
  `FK_TEMPLATEID` INT(255) ,
  `FK_CONFIGURATIONID` INT(255),
  FOREIGN KEY (FK_TEMPLATEID) REFERENCES TEMPLATE(TEMPLATEID),
  FOREIGN KEY (FK_CONFIGURATIONID) REFERENCES CONFIGURATION(CONFIGURATIONID),
  PRIMARY KEY (FK_TEMPLATEID, FK_CONFIGURATIONID));

    INSERT INTO AUTHORISATION VALUES
    (NULL,"ADMIN"),
    (NULL,"TEACHER"),
    (NULL,"GUEST");

    INSERT INTO USER VALUES
    (NULL,"K","K",1),
     (NULL,"DRESEN","DRESEN",2),
    (NULL,"MONIKA","TEST",3);
	
	INSERT INTO TEMPLATE (TITLE, FK_USERID) VALUES 
	('KENJIS', 1), 
	('MONIS', 3);
	
	INSERT INTO CONFIGURATION (NAME) VALUES 
	('KOMPETENZEN'),  
	('HANDLUNGSPRODUKT');
	
	INSERT INTO TEMPLATE_CONFIGURATION (FK_TEMPLATEID, FK_CONFIGURATIONID) VALUES 
	(1, 1),  
	(2,1),  
	(1,2);